//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC_Ed_Services.TafeDBServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/ABCEdWCFSerivce.Class")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateEnrolledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateEnrolled {
            get {
                return this.DateEnrolledField;
            }
            set {
                if ((this.DateEnrolledField.Equals(value) != true)) {
                    this.DateEnrolledField = value;
                    this.RaisePropertyChanged("DateEnrolled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentID {
            get {
                return this.StudentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIDField, value) != true)) {
                    this.StudentIDField = value;
                    this.RaisePropertyChanged("StudentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentName {
            get {
                return this.StudentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNameField, value) != true)) {
                    this.StudentNameField = value;
                    this.RaisePropertyChanged("StudentName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/ABCEdWCFSerivce.Class")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseIDField, value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TafeDBServiceReference.ITafeDBService")]
    public interface ITafeDBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITafeDBService/insertStudent", ReplyAction="http://tempuri.org/ITafeDBService/insertStudentResponse")]
        int insertStudent(string id, string name, System.DateTime dateEnrolled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITafeDBService/insertStudent", ReplyAction="http://tempuri.org/ITafeDBService/insertStudentResponse")]
        System.Threading.Tasks.Task<int> insertStudentAsync(string id, string name, System.DateTime dateEnrolled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITafeDBService/insertCourse", ReplyAction="http://tempuri.org/ITafeDBService/insertCourseResponse")]
        int insertCourse(string id, string name, decimal cost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITafeDBService/insertCourse", ReplyAction="http://tempuri.org/ITafeDBService/insertCourseResponse")]
        System.Threading.Tasks.Task<int> insertCourseAsync(string id, string name, decimal cost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITafeDBService/viewStudents", ReplyAction="http://tempuri.org/ITafeDBService/viewStudentsResponse")]
        System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Student> viewStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITafeDBService/viewStudents", ReplyAction="http://tempuri.org/ITafeDBService/viewStudentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Student>> viewStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITafeDBService/viewCourses", ReplyAction="http://tempuri.org/ITafeDBService/viewCoursesResponse")]
        System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Course> viewCourses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITafeDBService/viewCourses", ReplyAction="http://tempuri.org/ITafeDBService/viewCoursesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Course>> viewCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITafeDBService/enrol", ReplyAction="http://tempuri.org/ITafeDBService/enrolResponse")]
        int enrol(string courseId, string studentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITafeDBService/enrol", ReplyAction="http://tempuri.org/ITafeDBService/enrolResponse")]
        System.Threading.Tasks.Task<int> enrolAsync(string courseId, string studentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITafeDBService/getEnrolmentsForStudent", ReplyAction="http://tempuri.org/ITafeDBService/getEnrolmentsForStudentResponse")]
        System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Course> getEnrolmentsForStudent(string studentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITafeDBService/getEnrolmentsForStudent", ReplyAction="http://tempuri.org/ITafeDBService/getEnrolmentsForStudentResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Course>> getEnrolmentsForStudentAsync(string studentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITafeDBService/getStudentsEnrolledInCourse", ReplyAction="http://tempuri.org/ITafeDBService/getStudentsEnrolledInCourseResponse")]
        System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Student> getStudentsEnrolledInCourse(string courseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITafeDBService/getStudentsEnrolledInCourse", ReplyAction="http://tempuri.org/ITafeDBService/getStudentsEnrolledInCourseResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Student>> getStudentsEnrolledInCourseAsync(string courseID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITafeDBServiceChannel : ABC_Ed_Services.TafeDBServiceReference.ITafeDBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TafeDBServiceClient : System.ServiceModel.ClientBase<ABC_Ed_Services.TafeDBServiceReference.ITafeDBService>, ABC_Ed_Services.TafeDBServiceReference.ITafeDBService {
        
        public TafeDBServiceClient() {
        }
        
        public TafeDBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TafeDBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TafeDBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TafeDBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int insertStudent(string id, string name, System.DateTime dateEnrolled) {
            return base.Channel.insertStudent(id, name, dateEnrolled);
        }
        
        public System.Threading.Tasks.Task<int> insertStudentAsync(string id, string name, System.DateTime dateEnrolled) {
            return base.Channel.insertStudentAsync(id, name, dateEnrolled);
        }
        
        public int insertCourse(string id, string name, decimal cost) {
            return base.Channel.insertCourse(id, name, cost);
        }
        
        public System.Threading.Tasks.Task<int> insertCourseAsync(string id, string name, decimal cost) {
            return base.Channel.insertCourseAsync(id, name, cost);
        }
        
        public System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Student> viewStudents() {
            return base.Channel.viewStudents();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Student>> viewStudentsAsync() {
            return base.Channel.viewStudentsAsync();
        }
        
        public System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Course> viewCourses() {
            return base.Channel.viewCourses();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Course>> viewCoursesAsync() {
            return base.Channel.viewCoursesAsync();
        }
        
        public int enrol(string courseId, string studentID) {
            return base.Channel.enrol(courseId, studentID);
        }
        
        public System.Threading.Tasks.Task<int> enrolAsync(string courseId, string studentID) {
            return base.Channel.enrolAsync(courseId, studentID);
        }
        
        public System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Course> getEnrolmentsForStudent(string studentID) {
            return base.Channel.getEnrolmentsForStudent(studentID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Course>> getEnrolmentsForStudentAsync(string studentID) {
            return base.Channel.getEnrolmentsForStudentAsync(studentID);
        }
        
        public System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Student> getStudentsEnrolledInCourse(string courseID) {
            return base.Channel.getStudentsEnrolledInCourse(courseID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.TafeDBServiceReference.Student>> getStudentsEnrolledInCourseAsync(string courseID) {
            return base.Channel.getStudentsEnrolledInCourseAsync(courseID);
        }
    }
}
