//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCEdWCFSerivce
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent
    {
        public string StudentID { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> DateEnrolled { get; set; }
    }
}
